name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
    - name: Run packages installation
      run: conan install . --build=missing -s compiler.libcxx=libstdc++11
    - name: Generate CMake files
      run: cmake ..
    - name: Build project
      run: cmake --build .
