name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create the build folder
      run: mkdir build && cd build
    - name: Generate CMake files
      run: cmake ..
    - name: Build project
      run: cmake --build .
